### ISSUE TITLE
Bug in Cullface

### ISSUE THREAD

**Issue by jtorresfabra** [cedricpinson/osg#49]
It seems a bug https://github.com/cedricpinson/osg/blob/master/src/osgPlugins/osgjs/WriteVisitor.cpp#L533

Shouldn't it be FRONT?

**Comment by cedricpinson** [comment]
It seems, probably a force of cull back, but it's maybe not the best place to do it. I Agree with you

**Comment by jtorresfabra** [comment]
Or maybe a copy paste bug....

**Comment by jtorresfabra** [comment]
Fixed in #59
